//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public System.Guid Id { get; set; }
        public System.Guid MainAccountSubsetId { get; set; }
        public Nullable<System.Guid> ContractSubsetId { get; set; }
        public Nullable<System.Guid> ContractDealTypeSubsetId { get; set; }
        public Nullable<System.Guid> ProjectSubsetId { get; set; }
        public Nullable<System.Guid> RightSubsetId { get; set; }
        public Nullable<System.Guid> ChannelSubsetId { get; set; }
        public Nullable<System.Guid> TerritorySubsetId { get; set; }
        public Nullable<System.Guid> LanguageSubsetId { get; set; }
        public Nullable<System.Guid> ContactLicenseeSubsetId { get; set; }
        public Nullable<System.Guid> ContactLicensorSubsetId { get; set; }
        public Nullable<System.Guid> ContactBillToSubsetId { get; set; }
        public Nullable<System.Guid> ContactRemitToSubsetId { get; set; }
        public Nullable<System.Guid> ContactSalesEntitySubsetId { get; set; }
        public Nullable<System.Guid> ContactSalespersonSubsetId { get; set; }
        public Nullable<System.Guid> ContactAgentSubsetId { get; set; }
        public Nullable<System.Guid> ContactDepartmentSubsetId { get; set; }
        public Nullable<System.Guid> ContactOtherSubsetId { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Subsets Subsets { get; set; }
        public virtual Subsets Subsets1 { get; set; }
        public virtual Subsets Subsets2 { get; set; }
        public virtual Subsets Subsets3 { get; set; }
        public virtual Subsets Subsets4 { get; set; }
        public virtual Subsets Subsets5 { get; set; }
        public virtual Subsets Subsets6 { get; set; }
        public virtual Subsets Subsets7 { get; set; }
        public virtual Subsets Subsets8 { get; set; }
        public virtual Subsets Subsets9 { get; set; }
        public virtual Subsets Subsets10 { get; set; }
        public virtual Subsets Subsets11 { get; set; }
        public virtual Subsets Subsets12 { get; set; }
        public virtual Subsets Subsets13 { get; set; }
        public virtual Subsets Subsets14 { get; set; }
        public virtual Subsets Subsets15 { get; set; }
        public virtual Subsets Subsets16 { get; set; }
    }
}
