//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditedTables
    {
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string PrimaryKeyFieldName { get; set; }
        public string ParentKeyFieldName { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    }
}
