//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoNumberDefaults
    {
        public int NextContractNo { get; set; }
        public int NextInvoiceNo { get; set; }
        public int NextAcqContractNo { get; set; }
        public string ContractNoPrefix { get; set; }
        public string InvoiceNoPrefix { get; set; }
        public string AcqContractNoPrefix { get; set; }
        public bool UseAutoContractNo { get; set; }
        public bool UseAutoInvoiceNo { get; set; }
        public bool UseAutoAcqContractNo { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public int Id { get; set; }
        public int NextRoyaltyReportNo { get; set; }
        public int NextParticipationsReportNo { get; set; }
    }
}
