//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__old_Currencies
    {
        public string ISOCode { get; set; }
        public string Name { get; set; }
        public decimal ExchangeRate { get; set; }
        public int SortOrder { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public System.Guid AuditId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool IsActive { get; set; }
    }
}
