//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EventSubscriptionsOld
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EventSubscriptionTemplateId { get; set; }
        public string PrimaryInstanceId { get; set; }
        public Nullable<bool> NoApprovalRequired { get; set; }
        public Nullable<bool> IsOneShotTrigger { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.Guid> WorkflowInstanceId { get; set; }
        public string WorkflowBookmarkName { get; set; }
        public string LocalSubscriptionBehaviorDescription { get; set; }
        public string GlobalSubscriptionBehaviorDescription { get; set; }
        public string SubscriptionConfigurationData { get; set; }
        public Nullable<System.Guid> EventSubscriptionStatusId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.DateTime> LastApprovedEventDate { get; set; }
    }
}
