//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_old_ContractProjectData
    {
        public System.Guid ContractId { get; set; }
        public System.Guid ProjectId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> NoticeOfDeliveryDate { get; set; }
        public string ProjectAlias { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<decimal> EpisodeRate { get; set; }
        public Nullable<System.DateTime> RevenueRecognizedDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.DateTime> TechnicalAcceptanceDate { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> OutsideDeliveryDate { get; set; }
        public Nullable<decimal> RecognizedRevenueAmount { get; set; }
    }
}
