//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_old_ContractGrossReceiptDispositions
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid RightId { get; set; }
        public int SortOrder { get; set; }
        public string PreRecoupmentPercentageNote { get; set; }
        public string PreRecoupmentFeeNote { get; set; }
        public string PostRecoupmentPercentageNote { get; set; }
        public string PostRecoupmentFeeNote { get; set; }
        public bool IsCostOffTheTop { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public decimal PreRecoupmentPercentage { get; set; }
        public decimal PostRecoupmentPercentage { get; set; }
        public decimal PreRecoupmentFeePercentage { get; set; }
        public decimal PostRecoupmentFeePercentage { get; set; }
    }
}
