//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoyaltyDefinitionTiers
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractRoyaltyDefinitionId { get; set; }
        public int TierNumber { get; set; }
        public Nullable<System.Guid> AttributeSetId { get; set; }
        public string CalculationMethod { get; set; }
        public string CalculationBasis { get; set; }
        public Nullable<decimal> SharePercent { get; set; }
        public Nullable<decimal> ShareAmount { get; set; }
        public string UpperLimitType { get; set; }
        public Nullable<decimal> UpperLimitValueLow { get; set; }
        public Nullable<decimal> UpperLimitValueHigh { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool IsUnlimited { get; set; }
        public string RecoupmentPeriod { get; set; }
    
        public virtual ContractRoyaltyDefinitionAttributeSets ContractRoyaltyDefinitionAttributeSets { get; set; }
        public virtual ContractRoyaltyDefinitions ContractRoyaltyDefinitions { get; set; }
        public virtual RoyaltyCalculationBasis RoyaltyCalculationBasis { get; set; }
        public virtual RoyaltyCalculationMethods RoyaltyCalculationMethods { get; set; }
        public virtual RoyaltyRecoupmentPeriods RoyaltyRecoupmentPeriods { get; set; }
        public virtual RoyaltyUpperLimitTypes RoyaltyUpperLimitTypes { get; set; }
    }
}
