//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoyaltyConsumptionHistory
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContractBillingGroupId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<System.Guid> RoyaltyReportId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> InvoiceLineItemId { get; set; }
        public Nullable<System.Guid> SourceInvoiceId { get; set; }
        public string RecordType { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountBaseCurrency { get; set; }
        public Nullable<System.Guid> ContractInvoiceScheduleItemId { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
        public Nullable<System.Guid> SourceScheduleItemId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> ParticipationsStatementId { get; set; }
    
        public virtual ContractBillingGroups ContractBillingGroups { get; set; }
        public virtual ContractVersionSets ContractVersionSets { get; set; }
        public virtual ParticipationsStatements ParticipationsStatements { get; set; }
        public virtual RoyaltyConsumptionHistoryRecordTypes RoyaltyConsumptionHistoryRecordTypes { get; set; }
        public virtual RoyaltyReports RoyaltyReports { get; set; }
        public virtual ContractInvoiceScheduleItems ContractInvoiceScheduleItems { get; set; }
        public virtual InvoiceLineItems InvoiceLineItems { get; set; }
        public virtual Invoices Invoices { get; set; }
        public virtual Invoices Invoices1 { get; set; }
        public virtual ContractInvoiceScheduleItems ContractInvoiceScheduleItems1 { get; set; }
    }
}
