//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractNetCardRightAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractNetCardRightAssignments()
        {
            this.ContractNetCardRightChannelAssignments = new HashSet<ContractNetCardRightChannelAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractNetCardId { get; set; }
        public System.Guid RightId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsInPerpetuity { get; set; }
        public System.Guid HoldBackTypeId { get; set; }
        public int HoldBackLength { get; set; }
        public Nullable<System.Guid> HoldbackFromRightGroupId { get; set; }
        public string Note { get; set; }
        public int RunCount { get; set; }
        public string RunCountNote { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool IsRunCountUnlimited { get; set; }
        public bool IsEstimatedStartDate { get; set; }
        public bool IsEstimatedEndDate { get; set; }
    
        public virtual ContractNetCards ContractNetCards { get; set; }
        public virtual Rights Rights { get; set; }
        public virtual HoldbackTypes HoldbackTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardRightChannelAssignments> ContractNetCardRightChannelAssignments { get; set; }
        public virtual Rights Rights1 { get; set; }
    }
}
