//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractShipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractShipments()
        {
            this.ContractShipmentMaterials = new HashSet<ContractShipmentMaterials>();
        }
    
        public System.Guid Id { get; set; }
        public string ContactNote { get; set; }
        public Nullable<System.Guid> ShippingCompanyId { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string AccountingNote { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractShipmentMaterials> ContractShipmentMaterials { get; set; }
        public virtual ShippingCompanies ShippingCompanies { get; set; }
        public virtual ContractVersionSets ContractVersionSets { get; set; }
    }
}
