//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractInvoiceScheduleItemFeeParameters
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractInvoiceScheduleItemId { get; set; }
        public string ExecutionTimingCode { get; set; }
        public string ContractFeeCalcDateMethodCode { get; set; }
        public int StatementSearchOffsetMonths { get; set; }
        public Nullable<decimal> ParameterModifier { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractFeeCalcDateMethods ContractFeeCalcDateMethods { get; set; }
        public virtual ContractFeeCalcExecutionTimings ContractFeeCalcExecutionTimings { get; set; }
        public virtual ContractInvoiceScheduleItems ContractInvoiceScheduleItems { get; set; }
    }
}
