//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLedgerStatementItems
    {
        public System.Guid Id { get; set; }
        public System.Guid StatementId { get; set; }
        public int SourceIdentifier { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid AreaId { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.Guid RightId { get; set; }
        public string CurrencyCode { get; set; }
        public decimal AmountLocalCurrency { get; set; }
        public decimal AmountBaseCurrency { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractLedgerStatements ContractLedgerStatements { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual LedgerStatementAreas LedgerStatementAreas { get; set; }
        public virtual LedgerStatementCategories LedgerStatementCategories { get; set; }
        public virtual Rights Rights { get; set; }
    }
}
