//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoyaltyDefinitionAttributeSets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractRoyaltyDefinitionAttributeSets()
        {
            this.ContractRoyaltyDefinitionTiers = new HashSet<ContractRoyaltyDefinitionTiers>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractRoyaltyDefinitionId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Attribute1 { get; set; }
        public Nullable<System.Guid> Attribute2 { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractRoyaltyDefinitions ContractRoyaltyDefinitions { get; set; }
        public virtual RoyaltyAttributes RoyaltyAttributes { get; set; }
        public virtual RoyaltyAttributes RoyaltyAttributes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitionTiers> ContractRoyaltyDefinitionTiers { get; set; }
    }
}
