//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLedgerStatements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractLedgerStatements()
        {
            this.ContractLedgerStatementItems = new HashSet<ContractLedgerStatementItems>();
        }
    
        public System.Guid Id { get; set; }
        public int SupportNumber { get; set; }
        public System.DateTime StatementDate { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public int FiscalPeriodCode { get; set; }
        public int FiscalYear { get; set; }
        public bool IsOutgoing { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
        public string Note { get; set; }
        public string SupportCode { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementItems> ContractLedgerStatementItems { get; set; }
        public virtual ContractVersionSets ContractVersionSets { get; set; }
    }
}
