//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractCardExclusionRightAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractCardExclusionRightAssignments()
        {
            this.ContractCardExclusionRightChannelAssignments = new HashSet<ContractCardExclusionRightChannelAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractCardExclusionId { get; set; }
        public System.Guid RightId { get; set; }
        public string Note { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Rights Rights { get; set; }
        public virtual ContractCardExclusions ContractCardExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionRightChannelAssignments> ContractCardExclusionRightChannelAssignments { get; set; }
    }
}
