//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTimelineItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractTimelineItems()
        {
            this.ContractTimelineItemChannels = new HashSet<ContractTimelineItemChannels>();
            this.ContractTimelineItemLanguages = new HashSet<ContractTimelineItemLanguages>();
            this.ContractTimelineItemProjects = new HashSet<ContractTimelineItemProjects>();
            this.ContractTimelineItemRights = new HashSet<ContractTimelineItemRights>();
            this.ContractTimelineItems1 = new HashSet<ContractTimelineItems>();
            this.ContractTimelineItemTerritories = new HashSet<ContractTimelineItemTerritories>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ContractTimelineItemTypeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public bool IsEstimate { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> OriginalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemChannels> ContractTimelineItemChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemLanguages> ContractTimelineItemLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemProjects> ContractTimelineItemProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemRights> ContractTimelineItemRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItems> ContractTimelineItems1 { get; set; }
        public virtual ContractTimelineItems ContractTimelineItems2 { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual ContractTimelineItemTypes ContractTimelineItemTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemTerritories> ContractTimelineItemTerritories { get; set; }
    }
}
