//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractCardExclusions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractCardExclusions()
        {
            this.ContractCardExclusionLanguageAssignments = new HashSet<ContractCardExclusionLanguageAssignments>();
            this.ContractCardExclusionProjectAssignments = new HashSet<ContractCardExclusionProjectAssignments>();
            this.ContractCardExclusionRightAssignments = new HashSet<ContractCardExclusionRightAssignments>();
            this.ContractCardExclusionTerritoryAssignments = new HashSet<ContractCardExclusionTerritoryAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractCardId { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
        public int CardNumber { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionLanguageAssignments> ContractCardExclusionLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionProjectAssignments> ContractCardExclusionProjectAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionRightAssignments> ContractCardExclusionRightAssignments { get; set; }
        public virtual ContractCards ContractCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionTerritoryAssignments> ContractCardExclusionTerritoryAssignments { get; set; }
    }
}
