//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractFeeCalcIngestStatements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractFeeCalcIngestStatements()
        {
            this.ContractFeeCalcIngestStatementInputValues = new HashSet<ContractFeeCalcIngestStatementInputValues>();
            this.ContractFeeCalcReports = new HashSet<ContractFeeCalcReports>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
        public string StatementTypeCode { get; set; }
        public System.DateTime StatementDate { get; set; }
        public Nullable<System.DateTime> StatementEndDate { get; set; }
        public System.DateTime CreateDateTimeUtc { get; set; }
        public Nullable<System.DateTime> ApprovalDateTimeUtc { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcIngestStatementInputValues> ContractFeeCalcIngestStatementInputValues { get; set; }
        public virtual ContractFeeCalcIngestStatementTypes ContractFeeCalcIngestStatementTypes { get; set; }
        public virtual ContractVersionSets ContractVersionSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcReports> ContractFeeCalcReports { get; set; }
    }
}
