//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractReleaseData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractReleaseData()
        {
            this.ContractReleaseBoxOffice = new HashSet<ContractReleaseBoxOffice>();
            this.ContractReleaseTerritories = new HashSet<ContractReleaseTerritories>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid RightGroupId { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> AvgTixPrice { get; set; }
        public string EnglishTranslation { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.DateTime> ExchangeRateDate { get; set; }
        public string LocalFilmTitle { get; set; }
        public string LocalRating { get; set; }
        public Nullable<System.Guid> PandAStatus { get; set; }
        public Nullable<decimal> PandATotal { get; set; }
        public string ReleaseTabName { get; set; }
        public Nullable<int> TotalNumberofPrints { get; set; }
        public bool UseAvgTixPrice { get; set; }
        public string CompetitiveLandscape { get; set; }
        public string TrailerInfo { get; set; }
        public string TheatreChainInfo { get; set; }
        public string ReleasePlan { get; set; }
        public string LicenseeReportNote { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public string ReleaseNote { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Rights Rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractReleaseBoxOffice> ContractReleaseBoxOffice { get; set; }
        public virtual Contracts Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractReleaseTerritories> ContractReleaseTerritories { get; set; }
    }
}
