//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.ContractAllocationRules = new HashSet<ContractAllocationRules>();
            this.ContractBillingGroups = new HashSet<ContractBillingGroups>();
            this.ContractFeeCalcInputs = new HashSet<ContractFeeCalcInputs>();
            this.ContractGrossReceiptDispositions = new HashSet<ContractGrossReceiptDispositions>();
            this.ContractHigherRankedParticipationsContracts = new HashSet<ContractHigherRankedParticipationsContracts>();
            this.ContractMaterials = new HashSet<ContractMaterials>();
            this.ContractNetCards = new HashSet<ContractNetCards>();
            this.ContractParties = new HashSet<ContractParties>();
            this.ContractProjectCategories = new HashSet<ContractProjectCategories>();
            this.ContractProjectPrices = new HashSet<ContractProjectPrices>();
            this.ContractProjectTelecastSchedules = new HashSet<ContractProjectTelecastSchedules>();
            this.ContractRevenueAllocations = new HashSet<ContractRevenueAllocations>();
            this.ContractRevenueCards = new HashSet<ContractRevenueCards>();
            this.ContractRoyaltyDeductionRules = new HashSet<ContractRoyaltyDeductionRules>();
            this.ContractRoyaltyDefinitions = new HashSet<ContractRoyaltyDefinitions>();
            this.ContractTimelineItems = new HashSet<ContractTimelineItems>();
            this.ContractVersionSets = new HashSet<ContractVersionSets>();
            this.ContractVersionSets2 = new HashSet<ContractVersionSets>();
            this.FinancialSummary = new HashSet<FinancialSummary>();
            this.FinancialSummary1 = new HashSet<FinancialSummary>();
            this.ProjectAltCards = new HashSet<ProjectAltCards>();
            this.RoyaltyIngestStatementLines = new HashSet<RoyaltyIngestStatementLines>();
            this.SavedSearchContracts = new HashSet<SavedSearchContracts>();
            this.ContractCards = new HashSet<ContractCards>();
            this.ContractConditions = new HashSet<ContractConditions>();
            this.ContractInvoiceScheduleItems = new HashSet<ContractInvoiceScheduleItems>();
            this.ContractJournalEntries = new HashSet<ContractJournalEntries>();
            this.ContractReleaseData = new HashSet<ContractReleaseData>();
            this.ContractReportingRegions = new HashSet<ContractReportingRegions>();
            this.ContractRoyaltyData = new HashSet<ContractRoyaltyData>();
            this.OtherDataAttributeValues = new HashSet<OtherDataAttributeValues>();
            this.WorkflowTransitionAttempts = new HashSet<WorkflowTransitionAttempts>();
        }
    
        public System.Guid Id { get; set; }
        public string ContractType { get; set; }
        public string SupportCode { get; set; }
        public System.Guid LicenseeId { get; set; }
        public string LicenseeAlias { get; set; }
        public System.Guid LicensorId { get; set; }
        public string LicensorAlias { get; set; }
        public string ContractCode { get; set; }
        public System.Guid StatusId { get; set; }
        public Nullable<System.Guid> DealStatusId { get; set; }
        public decimal Gross { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal Net { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartDateNote { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndDateNote { get; set; }
        public bool IsInPerpetuity { get; set; }
        public Nullable<System.Guid> BatchId { get; set; }
        public Nullable<int> BatchYear { get; set; }
        public Nullable<int> GroupNumber { get; set; }
        public System.Guid DealTypeId { get; set; }
        public Nullable<System.DateTime> DealMemoDate { get; set; }
        public Nullable<int> SalesCycle { get; set; }
        public Nullable<System.Guid> VideoFormatTypeId { get; set; }
        public Nullable<System.DateTime> FullyExecutedDate { get; set; }
        public Nullable<System.DateTime> NoticeOfDeliveryDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public bool IsCrossCollateralizedAllFilms { get; set; }
        public bool IsCrossCollateralizedAllRights { get; set; }
        public Nullable<System.Guid> SalesAgencyId { get; set; }
        public string SalesAgencyAlias { get; set; }
        public Nullable<System.Guid> CollectionAgencyId { get; set; }
        public string CollectionAgencyAlias { get; set; }
        public decimal EpisodeRate { get; set; }
        public string Note { get; set; }
        public string OfferNote { get; set; }
        public string PeriodNote { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public System.Guid ResponsiblePartyId { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
        public Nullable<System.DateTime> ContractSentDate { get; set; }
        public bool IsPowerOfAttorney { get; set; }
        public string PrintsAndAdvertisingMin { get; set; }
        public string PrintsAndAdvertisingMax { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public bool HasTheatricalReleaseCommitment { get; set; }
        public Nullable<System.DateTime> RevenueRecognizedDate { get; set; }
        public bool HasSellOffPeriod { get; set; }
        public Nullable<int> SellOffPeriodCount { get; set; }
        public string SellOffPeriodType { get; set; }
        public string SellOffNote { get; set; }
        public bool IsSellOffInPerpetuity { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string LegacyPk_Text { get; set; }
        public decimal SalesAgencyCommissionPercent { get; set; }
        public string SalesAgencyCommissionNote { get; set; }
        public Nullable<System.DateTime> NoticeOfAssignmentDate { get; set; }
        public Nullable<System.DateTime> TechnicalAcceptanceDate { get; set; }
        public string Broadcaster { get; set; }
        public bool IsCrossCollateralizedAllTerritories { get; set; }
        public Nullable<System.DateTime> SellOffEndDate { get; set; }
        public Nullable<decimal> SalesAgencyExpenseCap { get; set; }
        public decimal VatPercent { get; set; }
        public Nullable<System.DateTime> OutsideDeliveryDate { get; set; }
        public bool IsEstimatedStartDate { get; set; }
        public bool IsEstimatedEndDate { get; set; }
        public System.Guid SignatorId { get; set; }
        public string TerritorySummaryAll { get; set; }
        public string TerritorySummaryGranted { get; set; }
        public string RightGroupSummaryAll { get; set; }
        public string RightGroupSummaryGranted { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
        public byte MajorVersion { get; set; }
        public byte MinorVersion { get; set; }
        public string VersionNote { get; set; }
        public Nullable<System.Guid> BizAffairsDocumentId { get; set; }
        public Nullable<System.Guid> GLSubsetId { get; set; }
        public Nullable<System.Guid> TaxTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> SecondaryTaxTypeId { get; set; }
        public string DefaultContractCardViewTypeCode { get; set; }
        public string CreatedByUserName { get; set; }
        public bool ManualRevenueAllocationsIncludesTerritories { get; set; }
        public bool ManualRevenueAllocationsIncludesLanguages { get; set; }
        public bool ManualRevenueAllocationsIncludesChannels { get; set; }
        public bool ManualRevenueAllocationsIncludesRights { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool IsHistorical { get; set; }
        public Nullable<System.Guid> VersionOriginatedByContactId { get; set; }
        public string VersionNumber { get; set; }
        public Nullable<System.Guid> FeeCalcIngestStatementTemplateId { get; set; }
        public Nullable<System.Guid> WorkflowStateId { get; set; }
        public bool IsTransitioning { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Contacts Contacts1 { get; set; }
        public virtual Contacts Contacts2 { get; set; }
        public virtual Contacts Contacts3 { get; set; }
        public virtual Contacts Contacts4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRules> ContractAllocationRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractBillingGroups> ContractBillingGroups { get; set; }
        public virtual ContractCardViewType ContractCardViewType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcInputs> ContractFeeCalcInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractGrossReceiptDispositions> ContractGrossReceiptDispositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractHigherRankedParticipationsContracts> ContractHigherRankedParticipationsContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractMaterials> ContractMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCards> ContractNetCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractParties> ContractParties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractProjectCategories> ContractProjectCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractProjectPrices> ContractProjectPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractProjectTelecastSchedules> ContractProjectTelecastSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRevenueAllocations> ContractRevenueAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRevenueCards> ContractRevenueCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDeductionRules> ContractRoyaltyDeductionRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitions> ContractRoyaltyDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItems> ContractTimelineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractVersionSets> ContractVersionSets { get; set; }
        public virtual ContractVersionSets ContractVersionSets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractVersionSets> ContractVersionSets2 { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual FeeCalcIngestStatementTemplates FeeCalcIngestStatementTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialSummary> FinancialSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialSummary> FinancialSummary1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCards> ProjectAltCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestStatementLines> RoyaltyIngestStatementLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchContracts> SavedSearchContracts { get; set; }
        public virtual TaxTypes TaxTypes { get; set; }
        public virtual TaxTypes TaxTypes1 { get; set; }
        public virtual ContractBatches ContractBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCards> ContractCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractConditions> ContractConditions { get; set; }
        public virtual ContractDealStatuses ContractDealStatuses { get; set; }
        public virtual ContractDealTypes ContractDealTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItems> ContractInvoiceScheduleItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractJournalEntries> ContractJournalEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractReleaseData> ContractReleaseData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractReportingRegions> ContractReportingRegions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyData> ContractRoyaltyData { get; set; }
        public virtual Subsets Subsets { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        public virtual ContractTypes ContractTypes { get; set; }
        public virtual PeriodTypes PeriodTypes { get; set; }
        public virtual ResponsibleParties ResponsibleParties { get; set; }
        public virtual VideoFormatTypes VideoFormatTypes { get; set; }
        public virtual WorkflowStates WorkflowStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherDataAttributeValues> OtherDataAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowTransitionAttempts> WorkflowTransitionAttempts { get; set; }
    }
}
