//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoyaltyScheduleItemDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyItemId { get; set; }
        public System.Guid RoyaltyLineItemTypeId { get; set; }
        public string ScheduleItemType { get; set; }
        public int Sequence { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public string EstimatedCurrencyCode { get; set; }
        public decimal EstimatedExchangeRate { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string ActualCurrencyCode { get; set; }
        public decimal ActualExchangeRate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool IsRecoupable { get; set; }
        public Nullable<int> EstimatedUnitCount { get; set; }
        public Nullable<decimal> EstimatedUnitPrice { get; set; }
        public Nullable<int> ActualUnitCount { get; set; }
        public Nullable<decimal> ActualUnitPrice { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual ContractRoyaltyLineItemTypes ContractRoyaltyLineItemTypes { get; set; }
        public virtual ContractRoyaltyScheduleItems ContractRoyaltyScheduleItems { get; set; }
    }
}
