//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLedgerStatementsMappings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractLedgerStatementsMappings()
        {
            this.ContractLedgerStatementAreaMapping = new HashSet<ContractLedgerStatementAreaMapping>();
            this.ContractLedgerStatementCategoryMapping = new HashSet<ContractLedgerStatementCategoryMapping>();
            this.ContractLedgerStatementColumnMapping = new HashSet<ContractLedgerStatementColumnMapping>();
            this.ContractLedgerStatementCurrencyMapping = new HashSet<ContractLedgerStatementCurrencyMapping>();
            this.ContractLedgerStatementProjectMapping = new HashSet<ContractLedgerStatementProjectMapping>();
            this.ContractLedgerStatementRightMapping = new HashSet<ContractLedgerStatementRightMapping>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementAreaMapping> ContractLedgerStatementAreaMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementCategoryMapping> ContractLedgerStatementCategoryMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementColumnMapping> ContractLedgerStatementColumnMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementCurrencyMapping> ContractLedgerStatementCurrencyMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementProjectMapping> ContractLedgerStatementProjectMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractLedgerStatementRightMapping> ContractLedgerStatementRightMapping { get; set; }
    }
}
