//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractInvoiceScheduleItemDefaults
    {
        public System.Guid Id { get; set; }
        public int Sequence { get; set; }
        public Nullable<decimal> PercentOfGross { get; set; }
        public bool IsDueDateEstimated { get; set; }
        public bool IsDeposit { get; set; }
        public string Term { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.Guid ContractInvoiceScheduleItemDefaultSetId { get; set; }
    
        public virtual ContractInvoiceScheduleItemDefaultSets ContractInvoiceScheduleItemDefaultSets { get; set; }
    }
}
