//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractInvoiceScheduleItemAllocationsTemporary
    {
        public System.Guid ContractInvoiceScheduleItemId { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<System.Guid> RightId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> ChannelId { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ContractAllocationRuleId { get; set; }
        public bool IsForSystemDefaults { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> ContractInvoiceScheduleItemProjectId { get; set; }
        public Nullable<System.Guid> ContractInvoiceScheduleItemProjectInstallmentId { get; set; }
    }
}
