//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractNetCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractNetCards()
        {
            this.ContractNetCardLanguageAssignments = new HashSet<ContractNetCardLanguageAssignments>();
            this.ContractNetCardProjectAssignments = new HashSet<ContractNetCardProjectAssignments>();
            this.ContractNetCardRightAssignments = new HashSet<ContractNetCardRightAssignments>();
            this.ContractNetCardTerritoryAssignments = new HashSet<ContractNetCardTerritoryAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ContractCardId { get; set; }
        public string Name { get; set; }
        public int CardNumber { get; set; }
        public string LicenseTypeCode { get; set; }
        public Nullable<System.Guid> ContractCardCategoryId { get; set; }
        public string ViewTypeCode { get; set; }
        public string Note { get; set; }
        public bool IsCrossCollateralized { get; set; }
        public System.DateTime DateModified { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public string LegacyPk2 { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractCardCategories ContractCardCategories { get; set; }
        public virtual ContractCardViewType ContractCardViewType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardLanguageAssignments> ContractNetCardLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardProjectAssignments> ContractNetCardProjectAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardRightAssignments> ContractNetCardRightAssignments { get; set; }
        public virtual ContractCards ContractCards { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual LicenseTypes LicenseTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardTerritoryAssignments> ContractNetCardTerritoryAssignments { get; set; }
    }
}
