//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractFeeCalcInputTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractFeeCalcInputTypes()
        {
            this.ContractFeeCalcInputs = new HashSet<ContractFeeCalcInputs>();
        }
    
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsGuarantee { get; set; }
        public string TargetDateCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcInputs> ContractFeeCalcInputs { get; set; }
        public virtual FeeCalcInputTypeTargetDates FeeCalcInputTypeTargetDates { get; set; }
    }
}
