//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractLedgerStatementAreaMapping
    {
        public int ID { get; set; }
        public int ContractLedgerStatementMappingID { get; set; }
        public System.Guid AreaID { get; set; }
        public string ExternalName { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractLedgerStatementsMappings ContractLedgerStatementsMappings { get; set; }
        public virtual LedgerStatementAreas LedgerStatementAreas { get; set; }
    }
}
