//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractParties
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ContactId { get; set; }
        public System.Guid ContactRoleTypeId { get; set; }
        public Nullable<System.Guid> ContactAlternateNameId { get; set; }
        public Nullable<System.Guid> ContactMethodId { get; set; }
        public Nullable<System.Guid> SubContactId { get; set; }
        public string SubContactCustomName { get; set; }
        public string Note { get; set; }
        public int SortOrder { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public decimal CommissionPercent { get; set; }
    
        public virtual ContactAlternateNames ContactAlternateNames { get; set; }
        public virtual ContactMethods ContactMethods { get; set; }
        public virtual ContactRoleTypes ContactRoleTypes { get; set; }
        public virtual Contacts Contacts { get; set; }
        public virtual Contacts Contacts1 { get; set; }
        public virtual Contracts Contracts { get; set; }
    }
}
