//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractProjectCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractProjectCategories()
        {
            this.ContractFeeCalcInputs = new HashSet<ContractFeeCalcInputs>();
            this.ContractInvoiceScheduleItemProjects = new HashSet<ContractInvoiceScheduleItemProjects>();
            this.FinancialSummary = new HashSet<FinancialSummary>();
            this.ContractInvoiceScheduleItems = new HashSet<ContractInvoiceScheduleItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ProjectCategoryId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcInputs> ContractFeeCalcInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemProjects> ContractInvoiceScheduleItemProjects { get; set; }
        public virtual ProjectCategories ProjectCategories { get; set; }
        public virtual Contracts Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialSummary> FinancialSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItems> ContractInvoiceScheduleItems { get; set; }
    }
}
