//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractGrossReceiptDispositions
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid RightId { get; set; }
        public string DispositionTypeCode { get; set; }
        public string ContactRoleCode { get; set; }
        public decimal Percentage { get; set; }
        public string PercentageNote { get; set; }
        public bool IsCostOffTop { get; set; }
        public string Note { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> LegacyPk_Guid { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContactRoleTypeSystemCodes ContactRoleTypeSystemCodes { get; set; }
        public virtual DispositionTypes DispositionTypes { get; set; }
        public virtual Rights Rights { get; set; }
        public virtual Contracts Contracts { get; set; }
    }
}
