//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatuses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractStatuses()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string AcquisitionAvailabilityEffect { get; set; }
        public string SaleAvailabilityEffect { get; set; }
        public string NegotiationStageCode { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string PrintName { get; set; }
        public string ColorHex { get; set; }
    
        public virtual AvailabilityEffects AvailabilityEffects { get; set; }
        public virtual AvailabilityEffects AvailabilityEffects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual NegotiationStages NegotiationStages { get; set; }
        public virtual SystemUndeletableIds SystemUndeletableIds { get; set; }
    }
}
