//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRoyaltyReportingSchedulePeriods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractRoyaltyReportingSchedulePeriods()
        {
            this.ContractRoyaltyReportingSchedulePeriodDates = new HashSet<ContractRoyaltyReportingSchedulePeriodDates>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractRoyaltyReportingScheduleId { get; set; }
        public int PeriodNumber { get; set; }
        public Nullable<int> NumberOfStatements { get; set; }
        public bool IsInPerpetuity { get; set; }
        public string RecurrenceTypeCode { get; set; }
        public System.DateTime FirstPeriodEndDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyReportingSchedulePeriodDates> ContractRoyaltyReportingSchedulePeriodDates { get; set; }
        public virtual ContractRoyaltyReportingSchedules ContractRoyaltyReportingSchedules { get; set; }
        public virtual RecurrenceTypes RecurrenceTypes { get; set; }
    }
}
