//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRelationships
    {
        public System.Guid Id { get; set; }
        public System.Guid LeftContactId { get; set; }
        public System.Guid RightContactId { get; set; }
        public System.Guid ContactRelationshipTypeId { get; set; }
        public string Note { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContactRelationshipTypes ContactRelationshipTypes { get; set; }
        public virtual Contacts Contacts { get; set; }
        public virtual Contacts Contacts1 { get; set; }
    }
}
