//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractReleaseBoxOffice
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractReleaseDataId { get; set; }
        public System.DateTime BoxOfficeDate { get; set; }
        public Nullable<long> CumulativeActualLC { get; set; }
        public Nullable<long> CumulativeActualUSD { get; set; }
        public Nullable<long> CumulativeAdmissions { get; set; }
        public bool IsEnded { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Screens { get; set; }
        public Nullable<long> WeekActualLC { get; set; }
        public Nullable<long> WeekActualUSD { get; set; }
        public Nullable<long> WeekAdmissions { get; set; }
        public int WeekendNumber { get; set; }
        public Nullable<long> WeekendActualLC { get; set; }
        public Nullable<long> WeekendActualUSD { get; set; }
        public Nullable<long> WeekendAdmissions { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ContractReleaseData ContractReleaseData { get; set; }
    }
}
