//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAllocationRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractAllocationRules()
        {
            this.ContractAllocationRuleChannels = new HashSet<ContractAllocationRuleChannels>();
            this.ContractAllocationRuleLanguages = new HashSet<ContractAllocationRuleLanguages>();
            this.ContractAllocationRuleProjects = new HashSet<ContractAllocationRuleProjects>();
            this.ContractAllocationRuleRights = new HashSet<ContractAllocationRuleRights>();
            this.ContractAllocationRuleTerritories = new HashSet<ContractAllocationRuleTerritories>();
            this.ContractInvoiceScheduleItemProjects = new HashSet<ContractInvoiceScheduleItemProjects>();
            this.ContractRevenueCards = new HashSet<ContractRevenueCards>();
            this.ContractInvoiceScheduleItems = new HashSet<ContractInvoiceScheduleItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> InvoiceItemCategoryId { get; set; }
        public string CurrencyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleChannels> ContractAllocationRuleChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleLanguages> ContractAllocationRuleLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleProjects> ContractAllocationRuleProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleRights> ContractAllocationRuleRights { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual InvoiceItemCategories InvoiceItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleTerritories> ContractAllocationRuleTerritories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemProjects> ContractInvoiceScheduleItemProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRevenueCards> ContractRevenueCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItems> ContractInvoiceScheduleItems { get; set; }
    }
}
