//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Countries()
        {
            this.ContactMethods = new HashSet<ContactMethods>();
            this.CountryLanguages = new HashSet<CountryLanguages>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string ShortName { get; set; }
        public string ShortNameUpperCase { get; set; }
        public string FullName { get; set; }
        public string Iso2Code { get; set; }
        public string Iso3Code { get; set; }
        public string IsoNumeric { get; set; }
        public string IsoStatus { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMethods> ContactMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryLanguages> CountryLanguages { get; set; }
    }
}
