//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultContacts
    {
        public int Id { get; set; }
        public System.Guid LicensorId { get; set; }
        public System.Guid LicenseeId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.Guid VendorId { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Contacts Contacts1 { get; set; }
        public virtual Contacts Contacts2 { get; set; }
    }
}
