//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> CloseDateTime { get; set; }
        public string FromCurrencyCode { get; set; }
        public string ToCurrencyCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<System.DateTime> MarketDateTimeUtc { get; set; }
        public string SourceExchange { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Currencies Currencies1 { get; set; }
        public virtual ExchangeRateCloseDates ExchangeRateCloseDates { get; set; }
    }
}
