//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fields()
        {
            this.DisplayTemplateColumns = new HashSet<DisplayTemplateColumns>();
            this.SavedSearch = new HashSet<SavedSearch>();
            this.SavedSearchCriteria = new HashSet<SavedSearchCriteria>();
            this.SavedSearchView = new HashSet<SavedSearchView>();
        }
    
        public System.Guid Id { get; set; }
        public string TargetTableKey { get; set; }
        public string FieldName { get; set; }
        public string DisplayGroup { get; set; }
        public string DisplayName { get; set; }
        public string CriteriaBehavior { get; set; }
        public string ViewBehavior { get; set; }
        public int IsFunction { get; set; }
        public string AdditionalCriteria { get; set; }
        public string AllowedValuesViewName { get; set; }
        public int IsCriteriaField { get; set; }
        public int IsViewField { get; set; }
        public bool IsActiveCriteria { get; set; }
        public bool IsActiveView { get; set; }
        public bool IsDefaultView { get; set; }
        public Nullable<System.Guid> AttributeId { get; set; }
        public bool IsDefaultCriteria { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<int> DefaultCriteriaOrder { get; set; }
        public Nullable<int> DefaultViewOrder { get; set; }
    
        public virtual OtherDataAttributes OtherDataAttributes { get; set; }
        public virtual DisplayGroups DisplayGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisplayTemplateColumns> DisplayTemplateColumns { get; set; }
        public virtual Tables Tables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearch> SavedSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchCriteria> SavedSearchCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchView> SavedSearchView { get; set; }
    }
}
