//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialSummary
    {
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> ProducerContractId { get; set; }
        public decimal ProducerCommissionPercent { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> ContractProjectCategoryId { get; set; }
    
        public virtual ContractProjectCategories ContractProjectCategories { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual Contracts Contracts1 { get; set; }
    }
}
