//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investments
    {
        public System.Guid Id { get; set; }
        public System.Guid AgreementId { get; set; }
        public System.Guid ContactId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsProducer { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> InvestmentTypeId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Agreements Agreements { get; set; }
        public virtual InvestmentTypes InvestmentTypes { get; set; }
    }
}
