//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorPercentages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvestorPercentages()
        {
            this.PaymentItems = new HashSet<PaymentItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ScheduleId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid ContactId { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public bool IsExcludedFromPayments { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> PercentageTypeId { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual PercentageTypes PercentageTypes { get; set; }
        public virtual Schedules Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentItems> PaymentItems { get; set; }
    }
}
