//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceLineItems()
        {
            this.ContractFeeCalcReportLines = new HashSet<ContractFeeCalcReportLines>();
            this.ContractInvoiceScheduleItemProjectInstallments = new HashSet<ContractInvoiceScheduleItemProjectInstallments>();
            this.ContractRoyaltyConsumptionHistory = new HashSet<ContractRoyaltyConsumptionHistory>();
            this.InvoiceLineItemAllocations = new HashSet<InvoiceLineItemAllocations>();
            this.ParticipationsActivityLines = new HashSet<ParticipationsActivityLines>();
            this.C_old_ContractInvoiceScheduleItemProjects = new HashSet<C_old_ContractInvoiceScheduleItemProjects>();
            this.InvoiceLineItemPayments = new HashSet<InvoiceLineItemPayments>();
            this.ContractInvoiceScheduleItemProjectInvoiceLineItems = new HashSet<ContractInvoiceScheduleItemProjectInvoiceLineItems>();
            this.InvoiceLineItems1 = new HashSet<InvoiceLineItems>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public int Sequence { get; set; }
        public System.Guid ItemCategoryId { get; set; }
        public Nullable<System.Guid> GLAccountId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public string LegacyPk2 { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public decimal Rate { get; set; }
        public bool IsTaxable { get; set; }
        public string ItemCategorySystemCode { get; set; }
        public decimal AmountBaseCurrency { get; set; }
        public decimal Subtotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal LineTotal { get; set; }
        public Nullable<System.Guid> ApplyToInvoiceLineItemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcReportLines> ContractFeeCalcReportLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemProjectInstallments> ContractInvoiceScheduleItemProjectInstallments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyConsumptionHistory> ContractRoyaltyConsumptionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItemAllocations> InvoiceLineItemAllocations { get; set; }
        public virtual Invoices Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLines> ParticipationsActivityLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_old_ContractInvoiceScheduleItemProjects> C_old_ContractInvoiceScheduleItemProjects { get; set; }
        public virtual GLAccounts GLAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItemPayments> InvoiceLineItemPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemProjectInvoiceLineItems> ContractInvoiceScheduleItemProjectInvoiceLineItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItems> InvoiceLineItems1 { get; set; }
        public virtual InvoiceLineItems InvoiceLineItems2 { get; set; }
    }
}
