//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItemCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceItemCategories()
        {
            this.ContractAllocationRules = new HashSet<ContractAllocationRules>();
            this.ContractInvoiceScheduleItemDefaultSets = new HashSet<ContractInvoiceScheduleItemDefaultSets>();
            this.RevenueRecognitionMethodInvoiceCategories = new HashSet<RevenueRecognitionMethodInvoiceCategories>();
            this.InvoiceLineItemPaymentSplits = new HashSet<InvoiceLineItemPaymentSplits>();
            this.PaymentDisbursements = new HashSet<PaymentDisbursements>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool ExpandPayments { get; set; }
        public bool IsGain { get; set; }
        public bool IsContractRelated { get; set; }
        public string LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string ShortCode { get; set; }
        public Nullable<System.Guid> GLAccountId { get; set; }
        public string SystemCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRules> ContractAllocationRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemDefaultSets> ContractInvoiceScheduleItemDefaultSets { get; set; }
        public virtual InvoiceItemCategorySystemCodes InvoiceItemCategorySystemCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevenueRecognitionMethodInvoiceCategories> RevenueRecognitionMethodInvoiceCategories { get; set; }
        public virtual GLAccounts GLAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItemPaymentSplits> InvoiceLineItemPaymentSplits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDisbursements> PaymentDisbursements { get; set; }
        public virtual SystemUndeletableIds SystemUndeletableIds { get; set; }
    }
}
