//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceActionLogEntries
    {
        public System.Guid Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid ResponsiblePartyId { get; set; }
        public System.Guid LogActionId { get; set; }
        public System.Guid FunctionalAreaId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual FunctionalAreas FunctionalAreas { get; set; }
        public virtual LogActions LogActions { get; set; }
        public virtual ResponsibleParties ResponsibleParties { get; set; }
    }
}
