//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItemPayments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceLineItemPayments()
        {
            this.ParticipationsActivityLines = new HashSet<ParticipationsActivityLines>();
            this.InvoiceLineItemPaymentSplits = new HashSet<InvoiceLineItemPaymentSplits>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid InvoiceLineItemId { get; set; }
        public System.Guid PaymentId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLines> ParticipationsActivityLines { get; set; }
        public virtual InvoiceLineItems InvoiceLineItems { get; set; }
        public virtual Payments Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItemPaymentSplits> InvoiceLineItemPaymentSplits { get; set; }
    }
}
