//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Languages()
        {
            this.ContractAllocationRuleLanguages = new HashSet<ContractAllocationRuleLanguages>();
            this.ContractBillingGroupLanguages = new HashSet<ContractBillingGroupLanguages>();
            this.ContractCardExclusionLanguageAssignments = new HashSet<ContractCardExclusionLanguageAssignments>();
            this.ContractFeeCalcReportLineAllocations = new HashSet<ContractFeeCalcReportLineAllocations>();
            this.ContractFeeCalcReportRevenueProjectAllocations = new HashSet<ContractFeeCalcReportRevenueProjectAllocations>();
            this.ContractInvoiceScheduleItemAllocations = new HashSet<ContractInvoiceScheduleItemAllocations>();
            this.ContractNetCardLanguageAssignments = new HashSet<ContractNetCardLanguageAssignments>();
            this.ContractRevenueAllocations = new HashSet<ContractRevenueAllocations>();
            this.ContractRevenueCardAllocations = new HashSet<ContractRevenueCardAllocations>();
            this.ContractRoyaltyDeductionRuleLanguages = new HashSet<ContractRoyaltyDeductionRuleLanguages>();
            this.ContractRoyaltyDefinitionLanguages = new HashSet<ContractRoyaltyDefinitionLanguages>();
            this.ContractShipmentMaterials = new HashSet<ContractShipmentMaterials>();
            this.ContractTimelineItemLanguages = new HashSet<ContractTimelineItemLanguages>();
            this.InvoiceLineItemAllocations = new HashSet<InvoiceLineItemAllocations>();
            this.LanguageMembers = new HashSet<LanguageMembers>();
            this.LanguageMembers1 = new HashSet<LanguageMembers>();
            this.ParticipationsActivityLines = new HashSet<ParticipationsActivityLines>();
            this.ParticipationsReportLineShares = new HashSet<ParticipationsReportLineShares>();
            this.ProjectAltCardLanguageAssignments = new HashSet<ProjectAltCardLanguageAssignments>();
            this.RoyaltyIngestStatementLines = new HashSet<RoyaltyIngestStatementLines>();
            this.RoyaltyReportLines = new HashSet<RoyaltyReportLines>();
            this.RoyaltyReportLineShares = new HashSet<RoyaltyReportLineShares>();
            this.TerritoryLanguageMembers = new HashSet<TerritoryLanguageMembers>();
            this.ContractCardLanguageAssignments = new HashSet<ContractCardLanguageAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string TypeCode { get; set; }
        public string OriginalName { get; set; }
        public Nullable<System.Guid> GLSubsetId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAllocationRuleLanguages> ContractAllocationRuleLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractBillingGroupLanguages> ContractBillingGroupLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardExclusionLanguageAssignments> ContractCardExclusionLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcReportLineAllocations> ContractFeeCalcReportLineAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractFeeCalcReportRevenueProjectAllocations> ContractFeeCalcReportRevenueProjectAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractInvoiceScheduleItemAllocations> ContractInvoiceScheduleItemAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNetCardLanguageAssignments> ContractNetCardLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRevenueAllocations> ContractRevenueAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRevenueCardAllocations> ContractRevenueCardAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDeductionRuleLanguages> ContractRoyaltyDeductionRuleLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitionLanguages> ContractRoyaltyDefinitionLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractShipmentMaterials> ContractShipmentMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTimelineItemLanguages> ContractTimelineItemLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItemAllocations> InvoiceLineItemAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageMembers> LanguageMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageMembers> LanguageMembers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLines> ParticipationsActivityLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsReportLineShares> ParticipationsReportLineShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardLanguageAssignments> ProjectAltCardLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestStatementLines> RoyaltyIngestStatementLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLines> RoyaltyReportLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLineShares> RoyaltyReportLineShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerritoryLanguageMembers> TerritoryLanguageMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractCardLanguageAssignments> ContractCardLanguageAssignments { get; set; }
        public virtual Subsets Subsets { get; set; }
    }
}
