//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockoutDates
    {
        public System.Guid Id { get; set; }
        public byte EarliestMonth { get; set; }
        public short EarliestYear { get; set; }
        public byte LatestMonth { get; set; }
        public short LatestYear { get; set; }
        public byte CurrentMonth { get; set; }
        public short CurrentYear { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual SystemUndeletableIds SystemUndeletableIds { get; set; }
    }
}
