//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationsReportLineValues
    {
        public System.Guid Id { get; set; }
        public System.Guid ParticipationsReportLineId { get; set; }
        public System.Guid ParticipationsReportingColumnId { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountBaseCurrency { get; set; }
        public decimal DisallowedAmount { get; set; }
        public decimal DisallowedAmountBaseCurrency { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> ReleaseForLineShareReserveId { get; set; }
        public decimal PreRecoupmentAmount { get; set; }
        public decimal PreRecoupmentAmountBaseCurrency { get; set; }
        public decimal PostRecoupmentAmount { get; set; }
        public decimal PostRecoupmentAmountBaseCurrency { get; set; }
    
        public virtual ParticipationsReportingColumns ParticipationsReportingColumns { get; set; }
        public virtual ParticipationsReportLines ParticipationsReportLines { get; set; }
        public virtual ParticipationsReportLineShareReserves ParticipationsReportLineShareReserves { get; set; }
    }
}
