//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationsIngestionMappingCalculatedColumns
    {
        public System.Guid Id { get; set; }
        public System.Guid ParticipationsIngestionMappingId { get; set; }
        public System.Guid LeftInputColumnId { get; set; }
        public System.Guid RightInputColumnId { get; set; }
        public string CalculationOperation { get; set; }
        public System.Guid ResultantColumnId { get; set; }
        public bool IsSignReversed { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ParticipationsIngestionMappings ParticipationsIngestionMappings { get; set; }
        public virtual ParticipationsReportingColumns ParticipationsReportingColumns { get; set; }
        public virtual ParticipationsReportingColumns ParticipationsReportingColumns1 { get; set; }
        public virtual ParticipationsReportingColumns ParticipationsReportingColumns2 { get; set; }
    }
}
