//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationsReportLineShareCalculations
    {
        public System.Guid Id { get; set; }
        public System.Guid ParticipationsReportLineShareId { get; set; }
        public int TierNumber { get; set; }
        public decimal CalculatedTheirShareAmount { get; set; }
        public decimal Revenue { get; set; }
        public decimal Units { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ParticipationsReportLineShares ParticipationsReportLineShares { get; set; }
    }
}
