//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationsReportingColumns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipationsReportingColumns()
        {
            this.ContractHigherRankedParticipationsContracts = new HashSet<ContractHigherRankedParticipationsContracts>();
            this.ContractRoyaltyDeductionRuleReportingColumns = new HashSet<ContractRoyaltyDeductionRuleReportingColumns>();
            this.ContractRoyaltyDefinitionReserves = new HashSet<ContractRoyaltyDefinitionReserves>();
            this.ContractRoyaltyDefinitions = new HashSet<ContractRoyaltyDefinitions>();
            this.ContractRoyaltyDefinitions1 = new HashSet<ContractRoyaltyDefinitions>();
            this.ParticipationsActivityLineValues = new HashSet<ParticipationsActivityLineValues>();
            this.ParticipationsIngestionMappingCalculatedColumns = new HashSet<ParticipationsIngestionMappingCalculatedColumns>();
            this.ParticipationsIngestionMappingCalculatedColumns1 = new HashSet<ParticipationsIngestionMappingCalculatedColumns>();
            this.ParticipationsIngestionMappingCalculatedColumns2 = new HashSet<ParticipationsIngestionMappingCalculatedColumns>();
            this.ParticipationsIngestionMappingColumns = new HashSet<ParticipationsIngestionMappingColumns>();
            this.ParticipationsReportLineValues = new HashSet<ParticipationsReportLineValues>();
            this.ParticipationsReserveTypeReportingColumns = new HashSet<ParticipationsReserveTypeReportingColumns>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string SystemCode { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractHigherRankedParticipationsContracts> ContractHigherRankedParticipationsContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDeductionRuleReportingColumns> ContractRoyaltyDeductionRuleReportingColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitionReserves> ContractRoyaltyDefinitionReserves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitions> ContractRoyaltyDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitions> ContractRoyaltyDefinitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLineValues> ParticipationsActivityLineValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsIngestionMappingCalculatedColumns> ParticipationsIngestionMappingCalculatedColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsIngestionMappingCalculatedColumns> ParticipationsIngestionMappingCalculatedColumns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsIngestionMappingCalculatedColumns> ParticipationsIngestionMappingCalculatedColumns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsIngestionMappingColumns> ParticipationsIngestionMappingColumns { get; set; }
        public virtual ParticipationsReportingColumnTypes ParticipationsReportingColumnTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsReportLineValues> ParticipationsReportLineValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsReserveTypeReportingColumns> ParticipationsReserveTypeReportingColumns { get; set; }
    }
}
