//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationsStatementReportLines
    {
        public System.Guid Id { get; set; }
        public System.Guid ParticipationsStatementReportId { get; set; }
        public System.Guid ParticipationsReportLineId { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ParticipationsReportLines ParticipationsReportLines { get; set; }
        public virtual ParticipationsStatementReports ParticipationsStatementReports { get; set; }
    }
}
