//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDisbursements
    {
        public System.Guid Id { get; set; }
        public System.Guid PaymentId { get; set; }
        public System.Guid ItemCategoryId { get; set; }
        public Nullable<System.Guid> RecipientContactId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
        public decimal Amount { get; set; }
        public bool WasInvoiceReceived { get; set; }
        public string LicensorInvoiceNo { get; set; }
        public string SalesAgencyInvoiceNo { get; set; }
        public decimal BaseCurrencyAmount { get; set; }
        public Nullable<System.Guid> BankId { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual InvoiceItemCategories InvoiceItemCategories { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
