//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItemReceipts
    {
        public System.Guid Id { get; set; }
        public System.Guid PaymentItemId { get; set; }
        public System.Guid LedgerItemId { get; set; }
        public decimal ProjectedAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal OriginalAmount { get; set; }
        public Nullable<decimal> ActualTaxAmount { get; set; }
        public Nullable<decimal> ProjectedTaxAmount { get; set; }
        public Nullable<decimal> OriginalTaxAmount { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual LedgerItems LedgerItems { get; set; }
        public virtual PaymentItems PaymentItems { get; set; }
    }
}
