//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAltCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectAltCards()
        {
            this.ProjectAltCardChannelAssignments = new HashSet<ProjectAltCardChannelAssignments>();
            this.ProjectAltCardContractCards = new HashSet<ProjectAltCardContractCards>();
            this.ProjectAltCardLanguageAssignments = new HashSet<ProjectAltCardLanguageAssignments>();
            this.ProjectAltCardProjectAssignments = new HashSet<ProjectAltCardProjectAssignments>();
            this.ProjectAltCardProjectSelections = new HashSet<ProjectAltCardProjectSelections>();
            this.ProjectAltCardRightAssignments = new HashSet<ProjectAltCardRightAssignments>();
            this.ProjectAltCardTerritoryAssignments = new HashSet<ProjectAltCardTerritoryAssignments>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ContractId { get; set; }
        public int CardNumber { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardChannelAssignments> ProjectAltCardChannelAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardContractCards> ProjectAltCardContractCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardLanguageAssignments> ProjectAltCardLanguageAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardProjectAssignments> ProjectAltCardProjectAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardProjectSelections> ProjectAltCardProjectSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardRightAssignments> ProjectAltCardRightAssignments { get; set; }
        public virtual Contracts Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAltCardTerritoryAssignments> ProjectAltCardTerritoryAssignments { get; set; }
    }
}
