//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionAskingPrices
    {
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid RegionId { get; set; }
        public int Minimum { get; set; }
        public int Middle { get; set; }
        public int Asking { get; set; }
        public bool IsContractualMinimum { get; set; }
        public bool IsBaseCase { get; set; }
        public Nullable<System.DateTime> EstimatedSaleDate { get; set; }
        public string Note { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public int ProducerMinimum { get; set; }
        public int ProducerAsking { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Territories Territories { get; set; }
    }
}
