//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportExcelColumnSettingOverrides
    {
        public System.Guid ReportId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<double> Width { get; set; }
        public string Title { get; set; }
        public string HorizontalAlignment { get; set; }
        public string VerticalAlignment { get; set; }
        public string NumberFormat { get; set; }
        public string FontName { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<bool> WrapText { get; set; }
        public Nullable<int> Rotation { get; set; }
        public Nullable<bool> IncludeTotal { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ExcelHorizontalAlignments ExcelHorizontalAlignments { get; set; }
        public virtual ExcelVerticalAlignments ExcelVerticalAlignments { get; set; }
        public virtual Reports Reports { get; set; }
    }
}
