//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQueueItemEvents
    {
        public System.Guid Id { get; set; }
        public System.Guid ReportQueueItemId { get; set; }
        public System.Guid ReportQueueItemEventTypeId { get; set; }
        public System.DateTime EventDateTimeUTC { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ReportQueueItemEventTypes ReportQueueItemEventTypes { get; set; }
        public virtual ReportQueueItems ReportQueueItems { get; set; }
    }
}
