//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCriteriaDefaultSets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportCriteriaDefaultSets()
        {
            this.ReportCriteriaDefaultAmounts = new HashSet<ReportCriteriaDefaultAmounts>();
            this.ReportCriteriaDefaultDateChoices = new HashSet<ReportCriteriaDefaultDateChoices>();
            this.ReportCriteriaDefaultDates = new HashSet<ReportCriteriaDefaultDates>();
            this.ReportCriteriaDefaultDisplayChoices = new HashSet<ReportCriteriaDefaultDisplayChoices>();
            this.ReportCriteriaDefaults = new HashSet<ReportCriteriaDefaults>();
            this.ReportCriteriaDefaultStringValues = new HashSet<ReportCriteriaDefaultStringValues>();
            this.Reports = new HashSet<Reports>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultAmounts> ReportCriteriaDefaultAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultDateChoices> ReportCriteriaDefaultDateChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultDates> ReportCriteriaDefaultDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultDisplayChoices> ReportCriteriaDefaultDisplayChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaults> ReportCriteriaDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultStringValues> ReportCriteriaDefaultStringValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual SystemUndeletableIds SystemUndeletableIds { get; set; }
    }
}
