//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reports()
        {
            this.ReportQueueItems = new HashSet<ReportQueueItems>();
            this.ReportAvailableCriteriaTypes = new HashSet<ReportAvailableCriteriaTypes>();
            this.ReportCriteriaDefaultsDisplayItems = new HashSet<ReportCriteriaDefaultsDisplayItems>();
            this.ReportExcelColumnSettingOverrides = new HashSet<ReportExcelColumnSettingOverrides>();
            this.ReportExcelColumnSettings = new HashSet<ReportExcelColumnSettings>();
            this.ReportExcelConditionalFormatSettings = new HashSet<ReportExcelConditionalFormatSettings>();
            this.ReportGroupMembers = new HashSet<ReportGroupMembers>();
            this.ReportOutputsAvailable = new HashSet<ReportOutputsAvailable>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public int SortOrder { get; set; }
        public string PdfGeneratorClass { get; set; }
        public string ExcelGeneratorClass { get; set; }
        public string SortParameter { get; set; }
        public string PdfSQL { get; set; }
        public string ExcelSQL { get; set; }
        public System.DateTime ActivateDate { get; set; }
        public bool IsBuiltIn { get; set; }
        public System.Guid CriteriaDefaultSetId { get; set; }
        public string NameOverride { get; set; }
        public string DescriptionOverride { get; set; }
        public Nullable<int> SortOrderOverride { get; set; }
        public Nullable<System.Guid> CriteriaDefaultSetIdOverride { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool IncludePreviousActivity { get; set; }
        public string PreviousActivityFormatString { get; set; }
        public bool IncludePreviousAcqActivity { get; set; }
        public string PreviousAcqActivityFormatString { get; set; }
        public string Disclaimer { get; set; }
        public string SortParameterOverride { get; set; }
        public string PreviousActivityFormatStringOverride { get; set; }
        public string PreviousAcqActivityFormatStringOverride { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportQueueItems> ReportQueueItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAvailableCriteriaTypes> ReportAvailableCriteriaTypes { get; set; }
        public virtual ReportCriteriaDefaultsDateChoices ReportCriteriaDefaultsDateChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultsDisplayItems> ReportCriteriaDefaultsDisplayItems { get; set; }
        public virtual ReportCriteriaDefaultSets ReportCriteriaDefaultSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportExcelColumnSettingOverrides> ReportExcelColumnSettingOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportExcelColumnSettings> ReportExcelColumnSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportExcelConditionalFormatSettings> ReportExcelConditionalFormatSettings { get; set; }
        public virtual ReportExcelGlobalSettingOverrides ReportExcelGlobalSettingOverrides { get; set; }
        public virtual ReportExcelGlobalSettings ReportExcelGlobalSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportGroupMembers> ReportGroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportOutputsAvailable> ReportOutputsAvailable { get; set; }
    }
}
