//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCriteriaDefaultDateChoices
    {
        public System.Guid Id { get; set; }
        public System.Guid CriteriaSetId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> HoldbackEndDate { get; set; }
        public Nullable<System.DateTime> AgingDate { get; set; }
        public Nullable<System.DateTime> AcqEndDate { get; set; }
        public Nullable<System.DateTime> AcqHoldbackEndDate { get; set; }
        public Nullable<bool> IncludeEstimated { get; set; }
        public Nullable<bool> IncludeActual { get; set; }
        public Nullable<bool> FilterForOutstanding { get; set; }
        public Nullable<bool> IncludeTerms { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual ReportCriteriaDefaultSets ReportCriteriaDefaultSets { get; set; }
    }
}
