//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCriteriaTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportCriteriaTypes()
        {
            this.ReportAvailableCriteriaTypes = new HashSet<ReportAvailableCriteriaTypes>();
            this.ReportCriteria = new HashSet<ReportCriteria>();
            this.ReportCriteriaDefaults = new HashSet<ReportCriteriaDefaults>();
            this.ReportCriteriaDefaultStringValues = new HashSet<ReportCriteriaDefaultStringValues>();
            this.ReportCriteriaStringValues = new HashSet<ReportCriteriaStringValues>();
        }
    
        public string Name { get; set; }
        public string DataType { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public bool ColumnSelector { get; set; }
    
        public virtual DataTypes DataTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAvailableCriteriaTypes> ReportAvailableCriteriaTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteria> ReportCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaults> ReportCriteriaDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaDefaultStringValues> ReportCriteriaDefaultStringValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaStringValues> ReportCriteriaStringValues { get; set; }
    }
}
