//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQueueItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportQueueItems()
        {
            this.ReportQueueItemEvents = new HashSet<ReportQueueItemEvents>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ReportQueueItemStatusTypeId { get; set; }
        public System.Guid ReportId { get; set; }
        public string ReportOutputTypeName { get; set; }
        public string ReportCriteriaSessionId { get; set; }
        public string UserName { get; set; }
        public System.DateTime EnqueueDateTimeUTC { get; set; }
        public bool HasUserDownloaded { get; set; }
        public string ReportOutputFilePath { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string CustomFileName { get; set; }
        public string ServerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportQueueItemEvents> ReportQueueItemEvents { get; set; }
        public virtual ReportOutputs ReportOutputs { get; set; }
        public virtual ReportQueueItemStatusTypes ReportQueueItemStatusTypes { get; set; }
        public virtual Reports Reports { get; set; }
        public virtual ReportCriteriaSessions ReportCriteriaSessions { get; set; }
    }
}
