//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCriteriaSessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportCriteriaSessions()
        {
            this.ReportQueueItems = new HashSet<ReportQueueItems>();
            this.ReportAvailsKeys = new HashSet<ReportAvailsKeys>();
            this.ReportCriteria = new HashSet<ReportCriteria>();
            this.ReportCriteriaStringValues = new HashSet<ReportCriteriaStringValues>();
        }
    
        public string SessionId { get; set; }
        public System.DateTime LastAccessed { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportQueueItems> ReportQueueItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAvailsKeys> ReportAvailsKeys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteria> ReportCriteria { get; set; }
        public virtual ReportCriteriaBatchYearsChoices ReportCriteriaBatchYearsChoices { get; set; }
        public virtual ReportCriteriaDateChoices ReportCriteriaDateChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCriteriaStringValues> ReportCriteriaStringValues { get; set; }
    }
}
