//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLogs
    {
        public System.Guid Id { get; set; }
        public string SessionId { get; set; }
        public string ReportName { get; set; }
        public string ReportCriteria { get; set; }
        public string ReportCriteriaDates { get; set; }
        public string ReportCriteriaDateChoices { get; set; }
        public string ReportCriteriaBatchYearsChoices { get; set; }
        public string ReportCriteriaProjectDisplayChoices { get; set; }
        public System.DateTime StartDate { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.DateTime> CompletionDateUtc { get; set; }
    }
}
