//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoyaltyReports()
        {
            this.ContractRoyaltyConsumptionHistory = new HashSet<ContractRoyaltyConsumptionHistory>();
            this.ContractRoyaltyReportingSchedulePeriodDates = new HashSet<ContractRoyaltyReportingSchedulePeriodDates>();
            this.RoyaltyReportLines = new HashSet<RoyaltyReportLines>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ReportNumber { get; set; }
        public decimal ReportedOurShare { get; set; }
        public decimal ReportedOurShareBaseCurrency { get; set; }
        public decimal ExchangeRate { get; set; }
        public bool Hold { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string ReportingCurrencyCode { get; set; }
        public decimal ReportedOurShareReportingCurrency { get; set; }
        public decimal ReportingCurrencyExchangeRate { get; set; }
        public System.Guid ContractVersionSetId { get; set; }
        public Nullable<System.Guid> RoyaltyIngestStatementId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyConsumptionHistory> ContractRoyaltyConsumptionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyReportingSchedulePeriodDates> ContractRoyaltyReportingSchedulePeriodDates { get; set; }
        public virtual ContractVersionSets ContractVersionSets { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Invoices Invoices { get; set; }
        public virtual RoyaltyIngestStatements RoyaltyIngestStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLines> RoyaltyReportLines { get; set; }
    }
}
