//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyReportingColumns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoyaltyReportingColumns()
        {
            this.ContractRoyaltyDeductionRuleReportingColumns = new HashSet<ContractRoyaltyDeductionRuleReportingColumns>();
            this.RoyaltyIngestionMappingColumns = new HashSet<RoyaltyIngestionMappingColumns>();
            this.RoyaltyIngestStatementLineValues = new HashSet<RoyaltyIngestStatementLineValues>();
            this.RoyaltyReportLineValues = new HashSet<RoyaltyReportLineValues>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string SystemCode { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDeductionRuleReportingColumns> ContractRoyaltyDeductionRuleReportingColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestionMappingColumns> RoyaltyIngestionMappingColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestStatementLineValues> RoyaltyIngestStatementLineValues { get; set; }
        public virtual RoyaltyReportingColumnTypes RoyaltyReportingColumnTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLineValues> RoyaltyReportLineValues { get; set; }
    }
}
