//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyIngestionMappingColumns
    {
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyIngestionMappingId { get; set; }
        public short ExcelColumn { get; set; }
        public string SystemCode { get; set; }
        public Nullable<System.Guid> RoyaltyReportingColumnId { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string ApiPropertyName { get; set; }
    
        public virtual RoyaltyIngestionMappingColumnTypes RoyaltyIngestionMappingColumnTypes { get; set; }
        public virtual RoyaltyIngestionMappings RoyaltyIngestionMappings { get; set; }
        public virtual RoyaltyReportingColumns RoyaltyReportingColumns { get; set; }
    }
}
