//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyReportLines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoyaltyReportLines()
        {
            this.RoyaltyReportLineShares = new HashSet<RoyaltyReportLineShares>();
            this.RoyaltyReportLineValues = new HashSet<RoyaltyReportLineValues>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyReportId { get; set; }
        public int XlsLineNumber { get; set; }
        public Nullable<System.Guid> SkuId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> RightId { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<System.Guid> ChannelId { get; set; }
        public Nullable<System.Guid> Attribute1Id { get; set; }
        public Nullable<System.Guid> Attribute2Id { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.Guid> ProjectCategoryId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual ProjectCategories ProjectCategories { get; set; }
        public virtual Rights Rights { get; set; }
        public virtual RoyaltyAttributes RoyaltyAttributes { get; set; }
        public virtual RoyaltyAttributes RoyaltyAttributes1 { get; set; }
        public virtual RoyaltyReports RoyaltyReports { get; set; }
        public virtual Territories Territories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLineShares> RoyaltyReportLineShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLineValues> RoyaltyReportLineValues { get; set; }
    }
}
