//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyReportLineShares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoyaltyReportLineShares()
        {
            this.RoyaltyReportLineShareCalculations = new HashSet<RoyaltyReportLineShareCalculations>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyReportLineId { get; set; }
        public Nullable<System.Guid> SkuId { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid TerritoryId { get; set; }
        public System.Guid RightId { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<System.Guid> ChannelId { get; set; }
        public System.Guid ResolvedContractRoyaltyDefinitionId { get; set; }
        public decimal AllocationPercent { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountBaseCurrency { get; set; }
        public bool IsOverridden { get; set; }
        public decimal CalculatedAmount { get; set; }
        public decimal CalculatedAmountBaseCurrency { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public decimal AmountReportingCurrency { get; set; }
        public decimal CalculatedAmountReportingCurrency { get; set; }
        public Nullable<System.Guid> ProjectCategoryId { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual ContractRoyaltyDefinitions ContractRoyaltyDefinitions { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual ProjectCategories ProjectCategories { get; set; }
        public virtual Rights Rights { get; set; }
        public virtual RoyaltyReportLines RoyaltyReportLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLineShareCalculations> RoyaltyReportLineShareCalculations { get; set; }
        public virtual Territories Territories { get; set; }
    }
}
