//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyAttributes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoyaltyAttributes()
        {
            this.ContractRoyaltyDefinitionAttributeSets = new HashSet<ContractRoyaltyDefinitionAttributeSets>();
            this.ContractRoyaltyDefinitionAttributeSets1 = new HashSet<ContractRoyaltyDefinitionAttributeSets>();
            this.ParticipationsActivityLines = new HashSet<ParticipationsActivityLines>();
            this.ParticipationsActivityLines1 = new HashSet<ParticipationsActivityLines>();
            this.RoyaltyIngestStatementLines = new HashSet<RoyaltyIngestStatementLines>();
            this.RoyaltyIngestStatementLines1 = new HashSet<RoyaltyIngestStatementLines>();
            this.RoyaltyReportLines = new HashSet<RoyaltyReportLines>();
            this.RoyaltyReportLines1 = new HashSet<RoyaltyReportLines>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortCode { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitionAttributeSets> ContractRoyaltyDefinitionAttributeSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoyaltyDefinitionAttributeSets> ContractRoyaltyDefinitionAttributeSets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLines> ParticipationsActivityLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationsActivityLines> ParticipationsActivityLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestStatementLines> RoyaltyIngestStatementLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyIngestStatementLines> RoyaltyIngestStatementLines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLines> RoyaltyReportLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoyaltyReportLines> RoyaltyReportLines1 { get; set; }
    }
}
