//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyReportLineShareCalculations
    {
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyReportLineShareId { get; set; }
        public int TierNumber { get; set; }
        public decimal CalculatedOurShareAmount { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<int> LegacyPk { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual RoyaltyReportLineShares RoyaltyReportLineShares { get; set; }
    }
}
