//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoyaltyIngestStatementLineValues
    {
        public System.Guid Id { get; set; }
        public System.Guid RoyaltyIngestStatementLineId { get; set; }
        public decimal Amount { get; set; }
        public System.Guid RoyaltyReportingColumnId { get; set; }
        public string TextValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual RoyaltyIngestStatementLines RoyaltyIngestStatementLines { get; set; }
        public virtual RoyaltyReportingColumns RoyaltyReportingColumns { get; set; }
    }
}
