//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedSearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SavedSearch()
        {
            this.FavoriteSearches = new HashSet<FavoriteSearches>();
            this.SavedSearchContracts = new HashSet<SavedSearchContracts>();
            this.SavedSearchInvoices = new HashSet<SavedSearchInvoices>();
            this.DisplayTemplates = new HashSet<DisplayTemplates>();
            this.SavedSearchCriteria = new HashSet<SavedSearchCriteria>();
            this.SavedSearchView = new HashSet<SavedSearchView>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> SortFieldId { get; set; }
        public string OwnedByUser { get; set; }
        public Nullable<System.DateTime> LastSaved { get; set; }
        public bool IsDefault { get; set; }
        public bool IsShared { get; set; }
        public string SearchType { get; set; }
        public string SearchProvider { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteSearches> FavoriteSearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchContracts> SavedSearchContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchInvoices> SavedSearchInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisplayTemplates> DisplayTemplates { get; set; }
        public virtual Fields Fields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchCriteria> SavedSearchCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedSearchView> SavedSearchView { get; set; }
        public virtual SearchTypes SearchTypes { get; set; }
    }
}
