//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSettingsMenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemSettingsMenuItems()
        {
            this.SystemSettingsMenuItems1 = new HashSet<SystemSettingsMenuItems>();
        }
    
        public string ParentCode { get; set; }
        public string NavigateUrl { get; set; }
        public string DisplayName { get; set; }
        public string ToolTip { get; set; }
        public int SortOrder { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsVisible { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemSettingsMenuItems> SystemSettingsMenuItems1 { get; set; }
        public virtual SystemSettingsMenuItems SystemSettingsMenuItems2 { get; set; }
    }
}
