//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAuditLogEntries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemAuditLogEntries()
        {
            this.SystemAuditLogEntryValues = new HashSet<SystemAuditLogEntryValues>();
        }
    
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public System.DateTime UtcDate { get; set; }
        public System.Guid EntityId { get; set; }
        public string EntityType { get; set; }
        public Nullable<System.Guid> ParentEntityId { get; set; }
        public string ActionType { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public Nullable<System.Guid> RootEntityId { get; set; }
        public string RootEntityType { get; set; }
        public Nullable<System.Guid> SecondaryRootEntityId { get; set; }
        public string SecondaryRootEntityType { get; set; }
    
        public virtual AuditActionTypes AuditActionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemAuditLogEntryValues> SystemAuditLogEntryValues { get; set; }
    }
}
