//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUndeletableIds
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual ContractMaterialDeliveryStatuses ContractMaterialDeliveryStatuses { get; set; }
        public virtual Rights Rights { get; set; }
        public virtual Territories Territories { get; set; }
        public virtual C__old_ContractMaterialItemTypes C__old_ContractMaterialItemTypes { get; set; }
        public virtual ChaseActions ChaseActions { get; set; }
        public virtual ContractDealTypes ContractDealTypes { get; set; }
        public virtual ContractDocumentTypes ContractDocumentTypes { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        public virtual FunctionalAreas FunctionalAreas { get; set; }
        public virtual HoldbackTypes HoldbackTypes { get; set; }
        public virtual InvoiceActionCategories InvoiceActionCategories { get; set; }
        public virtual InvoiceItemCategories InvoiceItemCategories { get; set; }
        public virtual LogActions LogActions { get; set; }
        public virtual OtherDataAttributeSets OtherDataAttributeSets { get; set; }
        public virtual RegionZones RegionZones { get; set; }
        public virtual ReportCriteriaDefaultSets ReportCriteriaDefaultSets { get; set; }
        public virtual ReportGroups ReportGroups { get; set; }
        public virtual ResponsibleParties ResponsibleParties { get; set; }
        public virtual LockoutDates LockoutDates { get; set; }
    }
}
