//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAuditLogEntryValues
    {
        public System.Guid Id { get; set; }
        public System.Guid SystemAuditLogEntryId { get; set; }
        public string FieldName { get; set; }
        public string ValueBefore { get; set; }
        public string ValueAfter { get; set; }
        public string DBAUpdateNote { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
    
        public virtual SystemAuditLogEntries SystemAuditLogEntries { get; set; }
    }
}
