//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabularCells
    {
        public System.Guid TabularFileId { get; set; }
        public int TabularPageNumber { get; set; }
        public int TabularColumnNumber { get; set; }
        public int TabularRowNumber { get; set; }
        public string CellText { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
    
        public virtual TabularColumns TabularColumns { get; set; }
        public virtual TabularFiles TabularFiles { get; set; }
        public virtual TabularRows TabularRows { get; set; }
    }
}
