//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitionAttemptActionResults
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransitionAttemptActionResults()
        {
            this.TransitionAttemptActionResultMessages = new HashSet<TransitionAttemptActionResultMessages>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TransitionActionId { get; set; }
        public System.Guid WorkflowTransitionAttemptId { get; set; }
        public System.DateTime DateRun { get; set; }
        public bool Success { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public int SeverityLevel { get; set; }
        public string TransitionActionStageCode { get; set; }
    
        public virtual TransitionActions TransitionActions { get; set; }
        public virtual TransitionActionStages TransitionActionStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAttemptActionResultMessages> TransitionAttemptActionResultMessages { get; set; }
        public virtual WorkflowTransitionAttempts WorkflowTransitionAttempts { get; set; }
    }
}
