//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowTransitionAttempts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowTransitionAttempts()
        {
            this.TransitionAttemptActionResults = new HashSet<TransitionAttemptActionResults>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public System.Guid WorkflowTransitionId { get; set; }
        public System.DateTime Date { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> DBAUpdateDate { get; set; }
        public string DBAUpdateNote { get; set; }
        public string Result { get; set; }
        public Nullable<bool> WasCompleted { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Contracts Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitionAttemptActionResults> TransitionAttemptActionResults { get; set; }
        public virtual WorkflowTransitions WorkflowTransitions { get; set; }
    }
}
